test_template: &test
  test_script:
    - git clone https://github.com/dnicolodi/python-siphash24.git
    - cd python-siphash24
    - python3 -m pip install .
    - python3 test.py

macos-arm64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:14
  install_script:
    - brew install python@3.10
    - echo "PATH=/opt/homebrew/opt/python@3.10/libexec/bin/:$PATH" >> $CIRRUS_ENV
  fix-pip_script:
    - python3 -m pip install --upgrade git+https://github.com/pypa/pip.git@main
  << : *test

debian-unstable_task:
  container:
    dockerfile: ci/debian-unstable.docker
  fix-pip_script:
    - python3 -m pip install --upgrade git+https://github.com/pypa/pip.git@refs/pull/11623/head
  << : *test

fedora-37_task:
  container:
    dockerfile: ci/fedora-37.docker
  << : *test

nixos_task:
  container:
    dockerfile: ci/nix.docker
  << : *test
