# container:
#   image: python:slim

macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-xcode:14

test_task:
  # pip_cache:
  #   folder: ~/.cache/pip
  #   fingerprint_script: echo $PYTHON_VERSION
  #   populate_script: pip install -r requirements.txt
  script:
    - brew install python@3.10
  env:
    PATH: /usr/local/opt/python@3.10/libexec/bin/:${PATH}
  script: echo $PATH
  script: ls -la /usr/local/opt/python@3.10/libexec/bin/
  script:
    - python -c 'print("Hello World!")'
    - python -c 'import sysconfig; print(sysconfig.get_platform())'
    - python -m pip install siphash24
    - python -c 'import siphash24; print(siphash24.siphash24(b'').hexdigest())'
