# macos_task:
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-xcode:14
#   test_script:
#     - find /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/ || true
#     - python3 -m pip install --upgrade -vv git+https://github.com/pypa/pip.git@refs/pull/11740/head
#     - python3 -m pip --version
#     # - git clone https://github.com/dnicolodi/python-siphash24.git
#     # - pushd python-siphash24
#     # - python3 -m pip install .
#     # - python3 -m venv .
#     # - bin/python -m pip install .
#     - python3 -m pip install --upgrade -vv git+https://github.com/pypa/pip.git@refs/pull/11740/head

macos_warnings_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14
  test_script:
    - sudo python3 -m pip install --upgrade git+https://github.com/pypa/pip.git
    - python3 -m pip --version
    - sudo python3 -m pip install --upgrade git+https://github.com/pypa/pip.git
    - python3 -m pip --version    
    - sudo python3 -m pip install --upgrade git+https://github.com/pypa/pip.git@refs/pull/11741/head
    - python3 -m pip --version

debian_task:
  container:
    dockerfile: ci/debian-unstable.docker
  test_script:
    - python3 -m pip install --upgrade git+https://github.com/pypa/pip.git@refs/pull/11740/head
    - python3 -m pip --version
    - git clone https://github.com/dnicolodi/python-siphash24.git
    - pushd python-siphash24
    - python3 -m pip install .
    - python3 -m venv .
    - bin/python -m pip install .
