macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14
  test_script:
    - python3 -m pip install --upgrade git+https://github.com/pypa/pip.git@refs/pull/11740/head
    - git clone https://github.com/dnicolodi/python-siphash24.git
    - pushd python-siphash24
    - python3 -m pip install .
    - python3 -m venv .
    - bin/python -m pip install .

debian_task:
  container:
    dockerfile: ci/debian-unstable.docker
  test_script:
    - python3 -m pip install --upgrade git+https://github.com/pypa/pip.git@refs/pull/11623/head
    - git clone https://github.com/dnicolodi/python-siphash24.git
    - pushd python-siphash24
    - python3 -m pip install .
    - python3 -m venv .
    - bin/python -m pip install .
